/**
 * Purchases API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { User } from '../model/models';
import { UserAuth } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * Logs user into the system via username amd password
     * 
     * @param userAuth The user object for login
     */
    loginUser(userAuth?: UserAuth, extraHttpRequestParams?: any): Observable<User>;

    /**
     * Logs out currently logged in user session
     * 
     */
    logoutUser(extraHttpRequestParams?: any): Observable<{}>;

}
