/**
 * Purchases API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Purchase } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PurchaseServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * Creates new Purchase
     * 
     * @param purchase Purchase
     */
    createPurchase(purchase?: Purchase, extraHttpRequestParams?: any): Observable<Purchase>;

    /**
     * Deletes existing Purchase
     * 
     * @param purchaseId Id of the Purchase
     */
    deletePurchase(purchaseId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Edits Purchase
     * 
     * @param purchase Purchase
     */
    editPurchase(purchase?: Purchase, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get Purchase by id
     * 
     * @param purchaseId Id of the Purchase
     * @param showAll Id of the Purchase
     */
    getPurchaseById(purchaseId: number, showAll?: boolean, extraHttpRequestParams?: any): Observable<Purchase>;

    /**
     * Get list of all Purchases
     * 
     * @param showAll Id of the Purchase
     */
    getPurchases(showAll?: boolean, extraHttpRequestParams?: any): Observable<Array<Purchase>>;

}
