/**
 * Purchases API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PurchaseTemplate } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PurchaseTemplateServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * Creates new PurchaseTemplate
     * 
     * @param purchaseTemplate Template
     */
    createTemplate(purchaseTemplate?: PurchaseTemplate, extraHttpRequestParams?: any): Observable<PurchaseTemplate>;

    /**
     * Deletes existing Purchase Template
     * 
     * @param templateId Id of the Purchase Template
     */
    deleteTemplate(templateId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Edit Purchase Template
     * 
     * @param purchaseTemplate Template
     */
    editTemplate(purchaseTemplate?: PurchaseTemplate, extraHttpRequestParams?: any): Observable<PurchaseTemplate>;

    /**
     * Get Purchase Template by id
     * 
     * @param templateId Id Purchase of the Template
     */
    getTemplateById(templateId: number, extraHttpRequestParams?: any): Observable<PurchaseTemplate>;

    /**
     * Get list of all Templates
     * 
     */
    getTemplates(extraHttpRequestParams?: any): Observable<Array<PurchaseTemplate>>;

}
