/**
 * Purchases API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PasswordUpdateHolder } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * Create user
     * 
     * @param user User
     */
    createUser(user?: User, extraHttpRequestParams?: any): Observable<User>;

    /**
     * Get list of all Users
     * 
     */
    getUsers(extraHttpRequestParams?: any): Observable<Array<User>>;

    /**
     * Update user password - disable with AD integration
     * 
     * @param passwordUpdateHolder 
     */
    updatePassword(passwordUpdateHolder: PasswordUpdateHolder, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Edit user
     * 
     * @param user User
     */
    updateUser(user?: User, extraHttpRequestParams?: any): Observable<User>;

}
