spring:
  data:
    jpa:
      repositories:
        enabled: true
        bootstrap-mode: default
  datasource:
    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: purchase
    password: purchase1
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5